run:
  timeout: 5m
  skip-files: [ ]
  skip-dirs: [ ]

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow # FIXME the issues reported must be reviewed.
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  goconst:
    min-len: 5
    min-occurrences: 3
  misspell:
    locale: US
  funlen:
    lines: -1
    statements: 40
  godox:
    keywords:
      - FIXME
  gofumpt:
    extra-rules: false
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/sirupsen/logrus
      - github.com/pkg/errors
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - sloppyReassign
      - rangeValCopy
      - octalLiteral
      - paramTypeCombine # already handle by gofumpt.extra-rules
      - exposedSyncMutex # FIXME MUST be fixed
    settings:
      hugeParam:
        sizeThreshold: 100
  stylecheck:
    go: "1.16"
    checks:
      - "all"
      - "-ST1005" # FIXME MUST be fixed

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - deadcode
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errname
#    - errorlint # TODO can be used in future.
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
#    - makezero # TODO can be used in future. Required to check the current reported issues.
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - tagliatelle
    - tenv
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude: []
  exclude-rules:
    - path: "(.+)_test.go"
      linters: ["goconst", "funlen"]
    - path: "testutils/utils.go"
      linters: ["funlen"]
    - path: "valkeyrie.go"
      linters: ["gochecknoglobals"]
