blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/kvtools/valkeyrie/discussions
    about: If you have a question, or are looking for advice, please post on our Discussions forum!

