version: "3.9"

# when running test local, you can specify the image version using the
# <service>_VERSION.
# Example, to run consul with the version 1.8:
# CONSUL_VERSION=1.8 make

services:
  consul:
    image: consul:${CONSUL_VERSION:-1.1.0}
    container_name: consul
    command: agent -server -bootstrap -client 0.0.0.0
    environment:
      CONSUL_LOCAL_CONFIG: '{"session_ttl_min": "1s"}'
    healthcheck:
      test: consul info | awk '/health_score/{if ($$3 >=1) exit 1; else exit 0}'
    ports:
      - 8500:8500

  etcd:
    image: quay.io/coreos/etcd:${ETCD_VERSION:-v3.3.8}
    container_name: etcd
    command: etcd --listen-client-urls 'http://0.0.0.0:4001' --advertise-client-urls 'http://127.0.0.1:4001'
    healthcheck:
      test: etcdctl --endpoints http://127.0.0.1:4001 cluster-health
    ports:
      - 4001:4001
    volumes:
      - /usr/share/ca-certificates/:/etc/ssl/certs

  zookeeper:
    image: zookeeper:${ZK_VERSION:-3.4.14}
    container_name: zookeeper
    healthcheck:
      test: nc -z localhost 2181 || exit 1
    ports:
      - 2181:2181

  redis:
    image: redis:${REDIS_VERSION:-4.0.10}
    container_name: redis
    healthcheck:
      test: redis-cli ping
    ports:
      - 6379:6379

  dynamodb:
    image: amazon/dynamodb-local:${DYNAMODB_VERSION:-1.18.0}
    container_name: dynamodb
    healthcheck:
      test: curl localhost:8000
    ports:
      - 8000:8000
