name: Build and test

on: [push, pull_request]

env:
  GOPROXY: https://proxy.golang.org
  GO111MODULE: on

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [1, 1.13]

    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Test tools
        run: |
          GO111MODULE=off go get golang.org/x/tools/cmd/cover
          GO111MODULE=off go get github.com/mattn/goveralls
          GO111MODULE=off go get golang.org/x/lint/golint
          GO111MODULE=off go get github.com/GeertJohan/fgt
          sudo apt-get install ca-certificates

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Download and check dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

      - name: Install stores
        run: |
          script/install_consul.sh 1.1.0
          script/install_etcd.sh 3.3.8
          script/install_zk.sh 3.4.14
          script/install_redis.sh 4.0.10
          script/install_dynamodb_local.sh

      - name: Run stores
        run: |
          ./consul agent -server -bootstrap -advertise=127.0.0.1 -data-dir /tmp/consul -config-file=./config.json 1>/dev/null &
          ./etcd/etcd --listen-client-urls 'http://0.0.0.0:4001' --advertise-client-urls 'http://127.0.0.1:4001' >/dev/null 2>&1 &
          ./zk/bin/zkServer.sh start ./zk/conf/zoo.cfg 1> /dev/null
          ./redis/src/redis-server &
          java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -inMemory &

      - name: Run tests
        run: |
          script/validate-gofmt
          go vet ./...
          fgt golint ./...
          go test -v -race ./...

      - name: Coverage report
        continue-on-error: true
        run: |
          script/coverage
          goveralls -service=github -coverprofile=goveralls.report -repotoken ${{ secrets.COVERALLS_TOKEN }}
