name: Build and test

on: [push, pull_request]

env:
  GOLANGCI_LINT_VERSION: v1.59.1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [stable, oldstable]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Download and check dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

      - name: Install golangci-lint ${{ env.GOLANGCI_LINT_VERSION }}
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}

      - name: Install Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          legacy: true

      - name: Install golangci-lint
        run: make validate

      - name: Run tests
        run: make test
        env:
          TEST_ARGS: "--count=1" # disable go test cache

      - name: Display docker-compose logs
        if: failure()
        run: docker-compose -f script/docker-compose.yml logs
