name: Build and test

on: [push, pull_request]

env:
  GOLANGCI_LINT_VERSION: v1.49.0

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: [1.18, 1.x]

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-${{ matrix.go-version }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-${{ matrix.go-version }}-go-

      - name: Download and check dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

      - name: Install golangci-lint ${{ env.GOLANGCI_LINT_VERSION }}
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}

      - name: Install Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          legacy: true

      - name: Install golangci-lint
        run: make validate

      - name: Run tests
        run: make test
        env:
          TEST_ARGS: "--count=1" # disable go test cache

      - name: Display docker-compose logs
        if: failure()
        run: docker-compose -f script/docker-compose.yml logs
